### ISSUE TITLE
Full version of the code?

### ISSUE THREAD

**Issue by Wuzimeng** [ylsung/ECoFLaP#1]
Hello, your work has aroused great interest in me, which makes me really want to delve deeper into understanding and reproducing the pruning process through code. Therefore, I wonder if the code in this repository is complete. Unfortunately, I noticed that at least the `lavis.compression.modify_model_with_weight_init` module, mentioned in train.py, is not included in the repository. 
Is this part necessary for pruning? Or, are you willing to release the complete code?

**Comment by ylsung** [comment]
The function is not used and you should be good to go to run the scripts in the README without issues (I didn't use the train.py at the end). The current approach is based on `lavis/compression/pruners`

For clarity, I just removed all the unused files, including train.py. Thanks!
