### ISSUE TITLE
Pruner for BLIP available?

### ISSUE THREAD

**Issue by Wuzimeng** [ylsung/ECoFLaP#3]
Hello, I found only `blipt5_wanda_pruner` in this repository, is it feasible to pruning `BLIP`(that is, with Bert as the backbone of language modal)? Or, is pruner for BLIP available?

**Comment by ylsung** [comment]
We just released the full version of our codes. Please find https://github.com/ylsung/ECoFLaP/blob/main/UPop/pruners/wanda_pruner.py for the BLIP pruner.
